//! Slash commands for TUI menu and Reedline completion (single source of truth).

pub const SLASH_COMMANDS: &[&str] = &[
    "/help",
    "/status",
    "/agent",
    "/plan",
    "/review",
    "/fix",
    "/test",
    "/skills",
    "/memory",
    "/compact",
    "/models",
    "/mcp",
    "/agents",
    "/logs",
    "/attach",
    "/image",
    "/config",
    "/doctor",
    "/model",
    "/permissions",
    "/permission-bypass",
    "/sessions",
    "/stop",
    "/exit",
    "/quit",
    "/q",
    "/clear",
    "/undo",
    "/redo",
    "/diff",
    "/cost",
    "/stats",
    "/auto-answer",
];
